# Generated by Django 5.1.7 on 2025-04-04 07:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "account_id",
                    models.UUIDField(
                        db_column="account_id",
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        blank=True, db_column="account_number", max_length=20, null=True
                    ),
                ),
                (
                    "bank_codes",
                    models.CharField(
                        blank=True, db_column="bank_codes", max_length=20, null=True
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        blank=True, db_column="account_type", max_length=20, null=True
                    ),
                ),
                (
                    "balance",
                    models.PositiveIntegerField(
                        blank=True, db_column="balance", null=True
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="create_at", null=True
                    ),
                ),
                (
                    "update_at",
                    models.DateTimeField(
                        auto_now=True, db_column="update_at", null=True
                    ),
                ),
            ],
            options={
                "db_table": "accounts",
            },
        ),
    ]
