# Generated by Django 5.1.7 on 2025-04-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="balance",
            field=models.PositiveIntegerField(
                blank=True, db_column="balance", null=True
            ),
        ),
    ]
