# Generated by Django 5.1.7 on 2025-04-02 09:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionHistory",
            fields=[
                (
                    "transaction_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "transaction_amount",
                    models.DecimalField(
                        db_column="transaction_amount", decimal_places=2, max_digits=18
                    ),
                ),
                (
                    "transaction_details",
                    models.CharField(db_column="transaction_details", max_length=255),
                ),
                (
                    "transaction_type",
                    models.CharField(db_column="transaction_type", max_length=10),
                ),
                (
                    "transaction_date",
                    models.DateTimeField(
                        auto_now_add=True, db_column="transaction_date"
                    ),
                ),
                (
                    "after_balance",
                    models.DecimalField(
                        db_column="after_balance", decimal_places=2, max_digits=18
                    ),
                ),
                (
                    "transaction_method",
                    models.CharField(db_column="transaction_method", max_length=20),
                ),
                (
                    "account",
                    models.ForeignKey(
                        db_column="account_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transaction_histories",
                        to="accounts.account",
                    ),
                ),
            ],
            options={
                "db_table": "transaction_history",
                "ordering": ["-transaction_date"],
            },
        ),
    ]
